github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
    repositories:   ["index.docker.io/paketobuildpacks/jattach","gcr.io/paketo-buildpacks/jattach"]
    register:       true
    registry_token: ${ secrets.PAKETO_BOT_GITHUB_TOKEN }

docker_credentials:
  - registry: gcr.io
    username: _json_key
    password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
  - registry: docker.io
    username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
    password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            jattach
  id:              jattach
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       jattach
    owner:      apangin
    repository: jattach
    tag_filter: v([\d.]*)
    token:      ${{ secrets.JAVA_GITHUB_TOKEN }}
