# Copyright 2018-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the JAttach binary"
  homepage = "https://github.com/paketo-buildpacks/jattach"
  id = "paketo-buildpacks/jattach"
  keywords = ["jattach", "java"]
  name = "Paketo Buildpack for JAttach"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/jattach/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "whether to contribute the JAttach binary at build time"
    name = "BP_JATTACH_ENABLED"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:apangin:jattach:2.1.0:*:*:*:*:*:*:*"]
    id = "jattach"
    name = "JAttach"
    purl = "pkg:generic/jattach@2.1.0?arch=amd64"
    sha256 = "07885fdc782e02e7302c6d190f54c3930afa10a38140365adf54076ec1086a8e"
    source = "https://github.com/apangin/jattach/archive/refs/tags/v2.1.tar.gz"
    source-sha256 = "bdb89f1769a9ecb30e121d6223213c04a697a0bed3429dca323a015813dbcdd8"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://github.com/jattach/jattach/releases/download/v2.1/jattach"
    version = "2.1.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/apangin/jattach/blob/master/LICENSE"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
